# Generated by Django 2.0.5 on 2018-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20180506_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=500, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=500, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='doctors/', width_field='image_width'),
        ),
    ]
