# Generated by Django 2.0.5 on 2018-05-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.Patient', verbose_name='Пациент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elqueueticket',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='el_queue', to='patients.Patient', verbose_name='Пациент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='patients.Patient', verbose_name='Пациент'),
            preserve_default=False,
        ),
    ]
