# Generated by Django 2.0.5 on 2018-05-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20180503_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_hours',
            field=models.ManyToManyField(default=[], related_name='_doctor_working_hours_+', to='doctors.WorkingHour', verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='week_day',
            field=models.CharField(choices=[('mo', 'Понедельник'), ('tu', 'Вторник'), ('we', 'Среда'), ('th', 'Четверг'), ('fr', 'Пятница'), ('sa', 'Суббота'), ('su', 'Воскресенье')], max_length=2, verbose_name='День недели'),
        ),
    ]
