# Generated by Django 2.0.5 on 2018-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='doctors/', width_field=500),
        ),
    ]
