# Generated by Django 2.0.5 on 2018-05-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20180506_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='review_rate',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
