# Generated by Django 2.0.5 on 2018-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='review_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
    ]
