# Generated by Django 2.0.5 on 2018-05-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_auto_20180506_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='review_rate',
        ),
    ]
