# Generated by Django 2.0.5 on 2018-05-06 15:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_remove_doctor_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='review_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=3),
        ),
    ]
