# Generated by Django 2.0.5 on 2018-05-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_auto_20180506_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='create_date',
        ),
    ]
